In [1]:
import numpy as np

In [7]:
liste=np.arange(1,21)

In [8]:
liste

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
liste[20:2:-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4])

In [26]:
print("3"+2)

TypeError: can only concatenate str (not "int") to str

In [27]:
a = "3"

In [32]:
b = "2"

In [36]:
a + b

'32'

In [44]:
x = np.array([1,2,3,7,8,9,4,5,6])

In [45]:
np.split(x, [3,7])

[array([1, 2, 3]), array([7, 8, 9, 4]), array([5, 6])]

In [46]:
x.sort()

In [47]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
liste.sort()

In [43]:
liste

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
a = np.array([1,7,5,4,8,0,9])

In [49]:
a.shape

(7,)

In [50]:
a[2]

5

In [51]:
samet = np.array([1,2,"a",3.14])

In [52]:
samet

array(['1', '2', 'a', '3.14'], dtype='<U11')

In [59]:
liste2 = [0,1,2,3,4]

In [60]:
liste2[-1] == liste2[5]

IndexError: list index out of range

In [63]:
liste3 = [0,1,2,3,4,5]

In [64]:
liste3[-1] == liste3[5]

True