In [1]:
import numpy as np

In [4]:
data_1 = np.loadtxt("hw_25000.csv", delimiter=',', skiprows=1)

In [6]:
np.set_printoptions(suppress=True)

In [7]:
data_1

array([[    1.     ,    65.78331,   112.9925 ],
       [    2.     ,    71.51521,   136.4873 ],
       [    3.     ,    69.39874,   153.0269 ],
       ...,
       [24998.     ,    64.69855,   118.2655 ],
       [24999.     ,    67.52918,   132.2682 ],
       [25000.     ,    68.87761,   124.8742 ]])

In [11]:
data_2 = np.genfromtxt("hw_25000.csv", delimiter=',', skip_header=1)

In [12]:
data_2

array([[    1.     ,    65.78331,   112.9925 ],
       [    2.     ,    71.51521,   136.4873 ],
       [    3.     ,    69.39874,   153.0269 ],
       ...,
       [24998.     ,    64.69855,   118.2655 ],
       [24999.     ,    67.52918,   132.2682 ],
       [25000.     ,    68.87761,   124.8742 ]])

In [13]:
np.array_equal(data_1, data_2)

True

In [15]:
#data_3 = np.loadtxt("hw_25000_NAN.csv", delimiter=',', skiprows=1)

In [16]:
data_4 = np.genfromtxt("hw_25000_NAN.csv", delimiter=',', skip_header=1)
data_4

array([[    1.     ,    65.78331,         nan],
       [    2.     ,    71.51521,         nan],
       [    3.     ,    69.39874,         nan],
       ...,
       [24998.     ,         nan,   118.2655 ],
       [24999.     ,         nan,   132.2682 ],
       [25000.     ,         nan,   124.8742 ]])

In [17]:
data_2

array([[    1.     ,    65.78331,   112.9925 ],
       [    2.     ,    71.51521,   136.4873 ],
       [    3.     ,    69.39874,   153.0269 ],
       ...,
       [24998.     ,    64.69855,   118.2655 ],
       [24999.     ,    67.52918,   132.2682 ],
       [25000.     ,    68.87761,   124.8742 ]])

In [18]:
np.save("cleaned_data_2",data_2)

In [20]:
np.savetxt("TEST.csv", data_2, delimiter=',', fmt='%.2f')