In [1]:
import numpy as np

In [2]:
ND = np.array([1,2,3,4,5])
ND

array([1, 2, 3, 4, 5])

In [3]:
PL = [1,2,3,4,5]
PL

[1, 2, 3, 4, 5]

In [4]:
ND = np.array([[1,2,3,4,5], [1,2,3,4,5]])
ND

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [5]:
ND.shape

(2, 5)

In [6]:
ND.ndim

2

In [7]:
ND.dtype

dtype('int32')

In [8]:
type(ND)

numpy.ndarray

In [9]:
ND.size

10

In [10]:
ND3 = np.array([[[1,2,3,4,5], [1,2,3,4,5]], [[1,2,3,4,5], [1,2,3,4,5]]])
ND3

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [11]:
ND3.ndim

3

In [12]:
ND3.size

20

In [13]:
ND3.shape

(2, 2, 5)

In [14]:
ND0 = np.array(4)
ND0

array(4)

In [15]:
type(ND0)

numpy.ndarray

In [16]:
ND0.ndim

0

In [17]:
NDX = np.array([4])
NDX

array([4])

In [18]:
NDX.ndim

1