In [3]:
import numpy as np

In [7]:
ND= np.eye(5)

In [8]:
ND

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
ND=np.arange(20)

In [11]:
ND

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
ND.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [13]:
NewVER=np.arange(20).reshape(2,10) #tek satırda da yazabiliyoruz(Biliyorsun ama canım yazmak istedi.istediğimi yazarım sanane)

In [14]:
NewVER

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [51]:
benimNpDizim= np.arange(15).reshape(3,5)

In [52]:
benimNpDizim

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
benimNpDizim[2][3] 

13

In [53]:
benimNpDizim[:,2] #2.satıra bu şekilde ulaşabiliri


array([ 2,  7, 12])

In [54]:
benimNpDizim[0,0] #sıfırıncı satır sıfırıncı stün

0

In [55]:
benimNpDizim[-1] #sondan başlatır.

array([10, 11, 12, 13, 14])

In [56]:
benimNpDizim[:,2] =44

In [57]:
benimNpDizim

array([[ 0,  1, 44,  3,  4],
       [ 5,  6, 44,  8,  9],
       [10, 11, 44, 13, 14]])

In [58]:
benimNpDizim = np.delete(benimNpDizim,0,axis=1) #sıfırıncı stün 
benimNpDizim

array([[ 1, 44,  3,  4],
       [ 6, 44,  8,  9],
       [11, 44, 13, 14]])

In [59]:
#yeni satır stün ekleme

In [60]:
benimNpDizim =np.append(benimNpDizim,[[7,7,7,7]],axis=0) #sona ekledik
#axis=0 satır demetir

In [62]:
benimNpDizim

array([[ 1, 44,  3,  4],
       [ 6, 44,  8,  9],
       [11, 44, 13, 14],
       [ 7,  7,  7,  7]])

In [73]:
#yeni bir örnek yapalım 
yeninumpydizim = np.arange(20).reshape(4,5)
yeninumpydizim

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
yeninumpydizim = np.insert(yeninumpydizim,1 ,[[7,7,7,7,7]], axis=0 ) #1.indexe sahip satıra [7,7,7,7,7] dizisini ekledik
yeninumpydizim

array([[ 0,  1,  2,  3,  4],
       [ 7,  7,  7,  7,  7],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [75]:
#şimdide satıra ekleme yapalım.insert ile  

yeninumpydizim = np.insert(yeninumpydizim, 2, [22,22,22,22,103], axis=1) # 2. index sahip stüna(axis=1) [22,22,22,22,103] dizisini ekledik.


In [76]:
yeninumpydizim

array([[  0,   1,  22,   2,   3,   4],
       [  7,   7,  22,   7,   7,   7],
       [  5,   6,  22,   7,   8,   9],
       [ 10,  11,  22,  12,  13,  14],
       [ 15,  16, 103,  17,  18,  19]])

In [79]:
yeninumpydizim[:] #numpy dizisini komple getirir. Aslında yeni yeninumpydizim ile hiç bir farkı yok !


array([[  0,   1,  22,   2,   3,   4],
       [  7,   7,  22,   7,   7,   7],
       [  5,   6,  22,   7,   8,   9],
       [ 10,  11,  22,  12,  13,  14],
       [ 15,  16, 103,  17,  18,  19]])

In [80]:
yeninumpydizim[1:3]

array([[ 7,  7, 22,  7,  7,  7],
       [ 5,  6, 22,  7,  8,  9]])

In [81]:
yeninumpydizim[:2,:2]

array([[0, 1],
       [7, 7]])

In [83]:
sliced_yeninumpydizim =yeninumpydizim[1:4, 2:4]
sliced_yeninumpydizim

array([[22,  7],
       [22,  7],
       [22, 12]])

In [84]:
sliced_yeninumpydizim[0,0] =99
sliced_yeninumpydizim

array([[99,  7],
       [22,  7],
       [22, 12]])

In [85]:
#yeni bir dizi oluşturup onun üzerinde  tekrar amaçlı aynı işlemleri yapalım
yeninumpydizim2= np.arange(12).reshape(3,4)
yeninumpydizim2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
sliced_yeninumpydizim2 = yeninumpydizim2[:2,:2]
sliced_yeninumpydizim2

array([[0, 1],
       [4, 5]])

In [88]:
sliced_yeninumpydizim2[0,0] = 100
sliced_yeninumpydizim2

array([[100,   1],
       [  4,   5]])

In [89]:
#slicing işlemini kopyalanmış bir dizide birakç işlem yapalım

sliced_2 = yeninumpydizim2[:2,:2].copy()
sliced_2

array([[100,   1],
       [  4,   5]])

In [90]:
sliced_2[0,0]

100

In [91]:
sliced_2[0,0] =1
sliced_2

array([[1, 1],
       [4, 5]])

In [92]:
yeninumpydizim2 # gördüğümüz gibi yeninumpydizim2 den hiç birşey değişmedi tüm operasyonları kopyalamış bir numpy dizisinde gerçekleşttirdik.

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [96]:
#yeni bir uygulama

ND = np.random.randint(0,10, (4,5))
ND
#(0,10) 0 ile 10 arasında (4,5) 4 satırlı 5 stünlü rastgele ! bir dizi oluşturduk.

array([[9, 8, 0, 1, 7],
       [6, 0, 9, 5, 3],
       [2, 0, 4, 4, 2],
       [4, 8, 2, 5, 1]])

In [97]:
ND[ND[:]>=5]  #5 den büyük olanı getirdik

array([9, 8, 7, 6, 9, 5, 8, 5])

In [98]:
ND[:]>=5  #5 den büyük mü (tüm sayılar için true false döndürür)

array([[ True,  True, False, False,  True],
       [ True, False,  True,  True, False],
       [False, False, False, False, False],
       [False,  True, False,  True, False]])

In [100]:
(ND[:] >=5) & (ND[:] <8) #and her iki koşulun olması gerekli 

array([[False, False, False, False,  True],
       [ True, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [102]:
ND[(ND[:] >=5) & (ND[:] <8)] # köşeli parantes ile yazarsak 5 den büyük 8 den küçük  elemanları getirir

array([7, 6, 5, 5])

In [103]:
ND +2 #tüm elemanları 2 artırır

array([[11, 10,  2,  3,  9],
       [ 8,  2, 11,  7,  5],
       [ 4,  2,  6,  6,  4],
       [ 6, 10,  4,  7,  3]])

In [104]:
ND + ND #farklı satır stüna sahip diziler toplanmaz !


array([[18, 16,  0,  2, 14],
       [12,  0, 18, 10,  6],
       [ 4,  0,  8,  8,  4],
       [ 8, 16,  4, 10,  2]])