In [1]:
import numpy as np

In [2]:
ND = np.random.randint(0,10, (4,4)) # Element - Wise
ND

array([[4, 9, 6, 3],
       [1, 3, 2, 6],
       [0, 5, 9, 2],
       [8, 4, 8, 1]])

In [4]:
ND2 = np.random.randint(0,10, (4,4))
ND2

array([[6, 2, 0, 7],
       [4, 2, 5, 0],
       [6, 1, 1, 8],
       [6, 1, 3, 4]])

In [5]:
ND + ND2

array([[10, 11,  6, 10],
       [ 5,  5,  7,  6],
       [ 6,  6, 10, 10],
       [14,  5, 11,  5]])

In [6]:
ND3 = np.random.randint(0,10, (2,2))
ND4 = np.random.randint(0,10, (1,3))

In [7]:
ND3

array([[3, 6],
       [9, 9]])

In [8]:
ND4

array([[2, 5, 8]])

In [10]:
ND3 + ND4

ValueError: operands could not be broadcast together with shapes (2,2) (1,3) 

In [11]:
ND5 = np.random.randint(0,10, (4,1))
ND6 = np.random.randint(0,10, (6,1))


In [12]:
ND5

array([[3],
       [2],
       [3],
       [7]])

In [13]:
ND6

array([[1],
       [4],
       [7],
       [0],
       [1],
       [8]])