In [1]:
import numpy as np

In [3]:
ND = np.arange(15).reshape(3,5)
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
ND[1,1]

6

In [5]:
ND[1][1]

6

In [6]:
ND[2, 3]

13

In [7]:
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
ND[1]

array([5, 6, 7, 8, 9])

In [10]:
ND[:, 2]

array([ 2,  7, 12])

In [11]:
ND[0,0]

0

In [12]:
ND[1]

array([5, 6, 7, 8, 9])

In [13]:
ND[-1]

array([10, 11, 12, 13, 14])

In [14]:
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
ND[-2, -2]

8

In [16]:
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
ND[0,0]

0

In [18]:
ND[0,0] = 99
ND

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
ND[:,2] = 44
ND

array([[99,  1, 44,  3,  4],
       [ 5,  6, 44,  8,  9],
       [10, 11, 44, 13, 14]])

In [20]:
ND

array([[99,  1, 44,  3,  4],
       [ 5,  6, 44,  8,  9],
       [10, 11, 44, 13, 14]])

In [21]:
ND = np.delete(ND, 0, axis=1)
ND

array([[ 1, 44,  3,  4],
       [ 6, 44,  8,  9],
       [11, 44, 13, 14]])

In [22]:
ND = np.delete(ND, -1, axis=0)
ND

array([[ 1, 44,  3,  4],
       [ 6, 44,  8,  9]])

In [23]:
ND

array([[ 1, 44,  3,  4],
       [ 6, 44,  8,  9]])

In [24]:
ND = np.append(ND, [[7,7,7,7]], axis=0)
ND

array([[ 1, 44,  3,  4],
       [ 6, 44,  8,  9],
       [ 7,  7,  7,  7]])

In [25]:
ND = np.insert(ND, 0, [[6,6,6,6]], axis=0)
ND

array([[ 6,  6,  6,  6],
       [ 1, 44,  3,  4],
       [ 6, 44,  8,  9],
       [ 7,  7,  7,  7]])

In [26]:
ND

array([[ 6,  6,  6,  6],
       [ 1, 44,  3,  4],
       [ 6, 44,  8,  9],
       [ 7,  7,  7,  7]])

In [28]:
ND = np.append(ND, [[99],[99],[99],[99]], axis=1)
ND

array([[ 6,  6,  6,  6, 99],
       [ 1, 44,  3,  4, 99],
       [ 6, 44,  8,  9, 99],
       [ 7,  7,  7,  7, 99]])

In [30]:
ND = np.insert(ND, 1, [[55],[55],[555],[22]], axis=1)
ND

array([[  6,  55,  55, 555,  22,   6,   6,   6,  99],
       [  1,  55,  55, 555,  22,  44,   3,   4,  99],
       [  6,  55,  55, 555,  22,  44,   8,   9,  99],
       [  7,  55,  55, 555,  22,   7,   7,   7,  99]])