In [1]:
import numpy as np

In [8]:
ND = np.arange(20).reshape(4,5)
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
ND[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
ND[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
ND[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
ND[:2,:2]

array([[0, 1],
       [5, 6]])

In [15]:
SLICED_ND = ND[1:4, 2:4]
SLICED_ND

array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [16]:
SLICED_ND[0,0] = 99
SLICED_ND

array([[99,  8],
       [12, 13],
       [17, 18]])

In [17]:
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 99,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
ND = np.arange(12).reshape(3,4)
ND

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
SLICED_ND = ND[:2,:2]
SLICED_ND

array([[0, 1],
       [4, 5]])

In [21]:
SLICED_ND[0,0] = 100
SLICED_ND

array([[100,   1],
       [  4,   5]])

In [22]:
ND

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [23]:
ND

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [24]:
SLICED_2 = ND[:2,:2].copy()
SLICED_2

array([[100,   1],
       [  4,   5]])

In [25]:
SLICED_2[0,0]

100

In [26]:
SLICED_2[0,0] = 1
SLICED_2

array([[1, 1],
       [4, 5]])

In [27]:
ND

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [28]:
ND = np.arange(12).reshape(3,4)
ND

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
SLICED_2 = ND[:2,:2].copy()

In [29]:
ND = np.arange(12).reshape(3,4)
ND

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
ND = np.random.randint(0,10, (4,5))
ND

array([[3, 7, 3, 5, 8],
       [7, 8, 7, 5, 0],
       [9, 7, 6, 1, 5],
       [9, 9, 9, 1, 9]])

In [32]:
ND[:] >=5

array([[False,  True, False,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True, False,  True],
       [ True,  True,  True, False,  True]])

In [34]:
ND[ND[:] >=5]

array([7, 5, 8, 7, 8, 7, 5, 9, 7, 6, 5, 9, 9, 9, 9])

In [35]:
ND

array([[3, 7, 3, 5, 8],
       [7, 8, 7, 5, 0],
       [9, 7, 6, 1, 5],
       [9, 9, 9, 1, 9]])

In [36]:
(ND[:] >=5) & (ND[:] <8)

array([[False,  True, False,  True, False],
       [ True, False,  True,  True, False],
       [False,  True,  True, False,  True],
       [False, False, False, False, False]])

In [37]:
ND[(ND[:] >=5) & (ND[:] <8)]

array([7, 5, 7, 7, 5, 7, 6, 5])